config/routes.rb
Omrails::Application.routes.draw do
  resources :pins

  devise_for :users
  get 'about' => 'pages#about' 

  root 'pins#index'

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url # This line won't work in Rails 4, instead, you'll have to do what I show below

  validates :description, presence: true
  validates :user_id, presence: true
  has_attached_file :image, styles: { medium: "320x240>"}
  validates_attachment :image, 
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }
  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}

  def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :token_authenticatable #, :validatable, :recoverable 

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  validates :name, :email, presence: true

  has_many :pins, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :image_remote_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "made by mindfulcoder", "http://mindfulcoder.com"%>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to "Mindful Picshare", root_path, class: "brand" %>
			<div class="nav-collapse">
				<ul class="nav">
					<li>
            <%= link_to "Home", root_path %>
          </li>
          <li>
            <%= link_to "About", about_path %>
          </li>
        </ul>
        <ul class="nav pull-right">

          <% if user_signed_in? %>
            <li><%= link_to "Add +", new_pin_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li> <%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Mindful Picshare</title>
	  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
	</head>
	<body>

		<%= render 'layouts/header' %>
		
		<div class="container">
			<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
		 </div>	
		<div class="container">
				<%= render 'layouts/footer' %>
		</div>
	 

	</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>
 <h1>Hello, lovely! </h1>
<% else%>
	<div class="center hero-unit">
	<center><h2><%= link_to "Mindful Picshare", "http://mindfulcoder.com"%></h2></center>
	<p></p>
	
	<p><center> <%= link_to 'Sign up now!',  new_user_registration_path , class: "btn btn-large btn-primary" %></center> </p>
	</div>
<% end %>

app/views/pages/about.html.erb
<h1>About </h1>
<p>
  <%= link_to "Mindful Picshare", "http://mindfulcoder.com"%>
  is an application built with
  <%= link_to "Ruby on Rails", "http://rubyonrails.org" %> 
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
 <h1>Hello, lovely! </h1>
<% else%>
	<div class="center hero-unit">
	<h1>Welcome!</h1>
	<p>
		to <%= link_to "Mindful Coder", "http://mindfulcoder.com"%>
	</p>
	<p>
	  <%= link_to "Sign up now!", "#"%>
	</p>
	<p> <%= link_to 'Sign up now!',  new_user_registration_path , class: "btn btn-large btn-primary" %> </p>
	</div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>
  <%= f.input :image, label: "upload an image" %> 
  <%= f.input :image_remote_url, label: "or enter a URL" %> 
  <%= f.input :description, as: :text, input_html: {rows: "3"} %>
    
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
  <%= link_to (image_tag pin.image(:medium)), pin %>
  <p class="description">
      <%= pin.description %>
  </p>
  <p>
    <strong>
        Posted by <%= pin.user.name %>
    </strong>
  </p>
  <% if current_user == pin.user %>
    <p>
      <%= link_to 'Edit', edit_pin_path(pin) %>
      <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</div>

app/views/pins/_pins.html.erb
<tr>
  <td><%= pin.description %></td>
  <td><%= link_to 'Show', pin %></td>
  <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
  <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>
<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
    $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
    $('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pin.image(:medium) %>
<p>
  <%= @pin.description %>
</p>

<p>
  <%= @pin.user.name %>
</p>
<% if current_user == @pin.user %>
	<%= link_to 'Edit', edit_pin_path(@pin) %> |
<% end %>
<%= link_to 'Back', pins_path %>

</div>
</div>
</div>